"""One source of truth for routing confidence and latency controls."""

RULE_DECISIVE_THRESHOLD = 0.94
KEYWORD_CANDIDATE_THRESHOLD = 0.42
# R7 migration-only fallback. Calibrated generations own their own threshold.
LEGACY_VECTOR_DIAGNOSTIC_THRESHOLD = 0.58
CANDIDATE_ADMISSION_THRESHOLD = 0.78
AMBIGUITY_MARGIN = 0.08
VECTOR_REQUEST_TIMEOUT_SECONDS = 1.5
SEMANTIC_WARMUP_TIMEOUT_SECONDS = 15.0
